name: Run tests

on:
  push:

jobs:
  main:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: yarn install

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Start app
      run: yarn start &

    - name: Wait for 30 seconds
      run: sleep 30s

    - name: Run tests
      run: yarn wdio

    - name: Discord Notification on Failure. Message
      if: failure() && github.ref == 'refs/heads/master'
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_STARTUPJS_TESTS_FAILED }}
        DISCORD_EMBEDS: |-
          [{
            "title": "> Tests failed! Check logs",
            "description": "[${{ github.event.head_commit.message }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})",
            "color": 16711680,
            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "author": {
                "name": "${{ github.actor }}",
                "url": "${{ github.server_url }}/${{ github.actor }}",
                "icon_url": "${{ github.server_url }}/${{ github.actor }}.png"
            }
          }]
